### ISSUE TITLE
[doc] Issue in "Requirements"

### ISSUE THREAD

**Issue by gabrielstein** [SUSE/doc-liberty#18]
Requirements:

https://documentation.suse.com/liberty/7/html/quickstart/index.html#requirements-quickstart

Could you please fix the wording here?

_SUSE Linux Enterprise Server (SLES) 15 is installed and running in the same network as the systems you want to register_

It should be something like: SUSE Linux Enterprise Server (SLES) 15  should be reachable by the systems you want to register.

Thanks!

**Comment by tahliar** [comment]
Thanks for the suggestion @gabrielstein! I've split that requirement into two, as it was kinda saying two separate things. 

Let me know if you're happy with this: https://github.com/SUSE/doc-liberty/pull/19

**Comment by gabrielstein** [comment]
@tahliar a bit too late because it was merged, but now it is better, thanks!
