### ISSUE TITLE
[doc] Issue in "REGISTERING CENTOS LINUX WITH RMT"

### ISSUE THREAD

**Issue by gusraggio** [SUSE/doc-liberty#30]
REGISTERING CENTOS LINUX WITH RMT:

https://documentation.suse.com/liberty/7/single-html/lite-quickstart/#pro-register-rhel-with-rmt

The file rmt-client-setup-res is not in the /srv/htdocs/www directory so step 1 fails.

Fix adding a step to copy the file from /usr/share/rmt/public/tools/rmt-client-setup-res

**Comment by tahliar** [comment]
Hi, thanks for opening this. 

However, the command in step 1 is this: 
`curl http://RMT_SERVER/tools/rmt-client-setup-res --output rmt-client-setup-res`

It's already using `/usr/share/rmt/public/tools/rmt-client-setup-res`, and has worked for me every time I've tested it; therefore there's nothing to fix here.
